set(LAPACKPATHS $ENV{LAPACK_PATH} $ENV{CPATH} $ENV{C_INCLUDE_PATH} $ENV{CPLUS_INCLUDE_PATH} $ENV{OBJC_INCLUDE_PATH} $ENV{LIBRARY_PATH} $ENV{LD_LIBRARY_PATH})

file(TO_CMAKE_PATH "${LAPACKPATHS}" LAPACKPATHS)

set(LAPACKPATHS ${LAPACKPATHS} ${CMAKE_SOURCE_DIR}/_EXTERNAL/LAPACK)




set(LAPACKSUFFIXESLIB
        /lib
	/build
)

set(LAPACKSUFFIXESINCLUDE
        /include
	/api
)


find_path(	LAPACK_INCLUDE_DIR lapacke.h 
		PATHS ${LAPACKPATHS}
		PATH_SUFFIXES ${LAPACKSUFFIXESINCLUDE}
		)

find_library(	LAPACK_LIBRARY1 NAME liblapacke.a
		PATHS ${LAPACKPATHS}
		PATH_SUFFIXES ${LAPACKSUFFIXESLIB}
		)

find_library(	LAPACK_LIBRARY2 NAME liblapack.a
		PATHS ${LAPACKPATHS}
		PATH_SUFFIXES ${LAPACKSUFFIXESLIB}
		)

find_library(	LAPACK_LIBRARY3 NAME libblas.a
		PATHS ${LAPACKPATHS}
		PATH_SUFFIXES ${LAPACKSUFFIXESLIB}
		)



set(LAPACK_LIBRARIES ${LAPACK_LIBRARY1} ${LAPACK_LIBRARY2} ${LAPACK_LIBRARY3})
set(LAPACK_INCLUDE_DIR ${LAPACK_INCLUDE_DIR} )

find_package_handle_standard_args(LAPACK  DEFAULT_MSG
                                  LAPACK_LIBRARIES LAPACK_INCLUDE_DIR)

mark_as_advanced(LAPACK_INCLUDE_DIR LAPACK_LIBRARIES )
