set(RAPIDXMLPATHS $ENV{RAPIDXML_PATH} $ENV{CPATH} $ENV{C_INCLUDE_PATH} $ENV{CPLUS_INCLUDE_PATH} $ENV{OBJC_INCLUDE_PATH} $ENV{LIBRARY_PATH} $ENV{LD_LIBRARY_PATH})

file(TO_CMAKE_PATH "${RAPIDXMLPATHS}" RAPIDXMLPATHS)

set(RAPIDXMLPATHS ${RAPIDXMLPATHS} ${CMAKE_SOURCE_DIR}/_EXTERNAL/RAPIDXML)




set(RAPIDXMLSUFFIXESLIB
        /lib
)

set(RAPIDXMLSUFFIXESINCLUDE
        /include
	/include/rapidxml
)


find_path(      RAPIDXML_INCLUDE_DIR rapidxml.hpp
                PATHS ${RAPIDXMLPATHS}
                PATH_SUFFIXES ${RAPIDXMLSUFFIXESINCLUDE}
                )

set(RAPIDXML_INCLUDE_DIR ${RAPIDXML_INCLUDE_DIR} )

find_package_handle_standard_args(RAPIDXML  DEFAULT_MSG
                                  RAPIDXML_INCLUDE_DIR)

mark_as_advanced(RAPIDXML_INCLUDE_DIR )

