set(AVOGADRO2PATHS $ENV{AVOGADRO2_PATH} $ENV{CPATH} $ENV{C_INCLUDE_PATH} $ENV{CPLUS_INCLUDE_PATH} $ENV{OBJC_INCLUDE_PATH} $ENV{LIBRARY_PATH} $ENV{LD_LIBRARY_PATH})

file(TO_CMAKE_PATH "${AVOGADRO2PATHS}" AVOGADRO2PATHS)

set(AVOGADRO2PATHS ${AVOGADRO2PATHS} ${CMAKE_SOURCE_DIR}/_EXTERNAL/AVOGADRO2/)


set(AVOGADRO2SUFFIXESINCLUDE
        avogadro2/scripts/inputGenerators
)

find_path(	AVOGADRO2_INCLUDE_DIR apbs.py gamessuk.py gaussian.py mopac.py nwchem.py qchem.py terachem.py 
		PATHS ${AVOGADRO2PATHS}
		PATH_SUFFIXES ${AVOGADRO2SUFFIXESINCLUDE}
		)

set(AVOGADRO2_INCLUDE_DIR ${AVOGADRO2_INCLUDE_DIR} )

find_package_handle_standard_args(AVOGADRO2  DEFAULT_MSG
                                  AVOGADRO2_INCLUDE_DIR)

mark_as_advanced(AVOGADRO2_INCLUDE_DIR)
