set(NLOPTPATHS $ENV{NLOPT_PATH} $ENV{CPATH} $ENV{C_INCLUDE_PATH} $ENV{CPLUS_INCLUDE_PATH} $ENV{OBJC_INCLUDE_PATH} $ENV{LIBRARY_PATH} $ENV{LD_LIBRARY_PATH})

file(TO_CMAKE_PATH "${NLOPTPATHS}" NLOPTPATHS)

set(NLOPTPATHS ${NLOPTPATHS} ${CMAKE_SOURCE_DIR}/_EXTERNAL/NLOPT)




set(NLOPTSUFFIXESLIB
        /lib
	/build
)

set(NLOPTSUFFIXESINCLUDE
        /include
	/api
)


find_path(	NLOPT_INCLUDE_DIR nlopt.hpp 
		PATHS ${NLOPTPATHS}
		PATH_SUFFIXES ${NLOPTSUFFIXESINCLUDE}
		)

find_library(	NLOPT_LIBRARY NAME libnlopt.a
		PATHS ${NLOPTPATHS}
		PATH_SUFFIXES ${NLOPTSUFFIXESLIB}
		)

set(NLOPT_LIBRARY ${NLOPT_LIBRARY} )
set(NLOPT_INCLUDE_DIR ${NLOPT_INCLUDE_DIR} )

find_package_handle_standard_args(NLOPT  DEFAULT_MSG
                                  NLOPT_LIBRARY NLOPT_INCLUDE_DIR)

MESSAGE("NLOPT" ${NLOPT_INCLUDE_DIR})

mark_as_advanced(NLOPT_INCLUDE_DIR NLOPT_LIBRARY )
